### ISSUE TITLE
建议使用gradle构建，并发布到jcenter或者maven仓库

### ISSUE THREAD

**Issue by snowdream** [evilbinary/HighlightTextEditor#1]
建议使用gradle构建，并发布到jcenter或者maven仓库

**Comment by evilbinary** [comment]
gradle 有用，但是源卡的不行。不是我不想。而且这个可以导入成gradle项目。

**Comment by snowdream** [comment]
@evilbinary 可以fq发布上去，使用第三方Maven镜像进行访问。

**Comment by evilbinary** [comment]
求推荐，

**Comment by snowdream** [comment]
fq 用XX-Net  https://github.com/XX-net/XX-Net
第三方Maven镜像 比如： http://maven.oschina.net/home.html
http://maven.oschina.net/help.html
