### ISSUE TITLE
替代EditText

### ISSUE THREAD

**Issue by FinalLody** [evilbinary/HighlightTextEditor#2]
EditText不适合用于代码编辑器, 因为它的性能随着文本量的增加而变慢, 这几乎难以忍受, 因此你需要基于View打造一个自定义的编辑视图. 这本该是有人研究的, 但是没有人想要开源.例如AIDE, QuickEdit.

**Comment by evilbinary** [comment]
性能还可以，看你怎么用，一般渲染可见页面就好了，然后文件大小，要自己分段处理。

**Comment by evilbinary** [comment]
其实我有个cl编辑器，还没开源出来，你可以先试试看，大文件不会卡，http://pan.baidu.com/s/1i3AO2NF 只是还没完成全部功能，等我这个编辑器造好换过去。
