### ISSUE TITLE
Execution failed for task ':ndkBuild'.

### ISSUE THREAD

**Issue by leonhhhhh** [evilbinary/HighlightTextEditor#4]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ndkBuild'.
> Process 'command '/Users/leon/Library/Android/sdk/ndk-bundle/ndk-build'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by evilbinary** [comment]
please provide more infomation

**Comment by evilbinary** [comment]
not any infomation will close
